// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protos/messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One      string `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two      int64  `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`
	Three    bool   `protobuf:"varint,3,opt,name=three,proto3" json:"three,omitempty"`
	FourNice string `protobuf:"bytes,4,opt,name=four_nice,json=fourNice,proto3" json:"four_nice,omitempty"`
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

func (x *SimpleMessage) GetTwo() int64 {
	if x != nil {
		return x.Two
	}
	return 0
}

func (x *SimpleMessage) GetThree() bool {
	if x != nil {
		return x.Three
	}
	return false
}

func (x *SimpleMessage) GetFourNice() string {
	if x != nil {
		return x.FourNice
	}
	return ""
}

type NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nested *SimpleMessage `protobuf:"bytes,1,opt,name=nested,proto3" json:"nested,omitempty"`
	Two    string         `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NestedMessage) GetNested() *SimpleMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *NestedMessage) GetTwo() string {
	if x != nil {
		return x.Two
	}
	return ""
}

type DoubleNestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoubleOne *NestedMessage `protobuf:"bytes,1,opt,name=double_one,json=doubleOne,proto3" json:"double_one,omitempty"`
	DoubleTwo *NestedMessage `protobuf:"bytes,2,opt,name=double_two,json=doubleTwo,proto3" json:"double_two,omitempty"`
}

func (x *DoubleNestedMessage) Reset() {
	*x = DoubleNestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleNestedMessage) ProtoMessage() {}

func (x *DoubleNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleNestedMessage.ProtoReflect.Descriptor instead.
func (*DoubleNestedMessage) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DoubleNestedMessage) GetDoubleOne() *NestedMessage {
	if x != nil {
		return x.DoubleOne
	}
	return nil
}

func (x *DoubleNestedMessage) GetDoubleTwo() *NestedMessage {
	if x != nil {
		return x.DoubleTwo
	}
	return nil
}

type MessageOneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Simpleoneof:
	//
	//	*MessageOneOf_S
	//	*MessageOneOf_I
	//	*MessageOneOf_M
	Simpleoneof isMessageOneOf_Simpleoneof `protobuf_oneof:"simpleoneof"`
}

func (x *MessageOneOf) Reset() {
	*x = MessageOneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOneOf) ProtoMessage() {}

func (x *MessageOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOneOf.ProtoReflect.Descriptor instead.
func (*MessageOneOf) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{3}
}

func (m *MessageOneOf) GetSimpleoneof() isMessageOneOf_Simpleoneof {
	if m != nil {
		return m.Simpleoneof
	}
	return nil
}

func (x *MessageOneOf) GetS() string {
	if x, ok := x.GetSimpleoneof().(*MessageOneOf_S); ok {
		return x.S
	}
	return ""
}

func (x *MessageOneOf) GetI() int64 {
	if x, ok := x.GetSimpleoneof().(*MessageOneOf_I); ok {
		return x.I
	}
	return 0
}

func (x *MessageOneOf) GetM() *SimpleMessage {
	if x, ok := x.GetSimpleoneof().(*MessageOneOf_M); ok {
		return x.M
	}
	return nil
}

type isMessageOneOf_Simpleoneof interface {
	isMessageOneOf_Simpleoneof()
}

type MessageOneOf_S struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3,oneof"`
}

type MessageOneOf_I struct {
	I int64 `protobuf:"varint,2,opt,name=i,proto3,oneof"`
}

type MessageOneOf_M struct {
	M *SimpleMessage `protobuf:"bytes,3,opt,name=m,proto3,oneof"`
}

func (*MessageOneOf_S) isMessageOneOf_Simpleoneof() {}

func (*MessageOneOf_I) isMessageOneOf_Simpleoneof() {}

func (*MessageOneOf_M) isMessageOneOf_Simpleoneof() {}

type ListMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SimpleMessage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListMessage) Reset() {
	*x = ListMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessage) ProtoMessage() {}

func (x *ListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessage.ProtoReflect.Descriptor instead.
func (*ListMessage) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessage) GetList() []*SimpleMessage {
	if x != nil {
		return x.List
	}
	return nil
}

type ComplexListMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DoubleNestedMessage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ComplexListMessage) Reset() {
	*x = ComplexListMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexListMessage) ProtoMessage() {}

func (x *ComplexListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexListMessage.ProtoReflect.Descriptor instead.
func (*ComplexListMessage) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ComplexListMessage) GetList() []*DoubleNestedMessage {
	if x != nil {
		return x.List
	}
	return nil
}

var File_protos_messages_proto protoreflect.FileDescriptor

var file_protos_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0x66, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f,
	0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x74, 0x77, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f,
	0x75, 0x72, 0x5f, 0x6e, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x6f, 0x75, 0x72, 0x4e, 0x69, 0x63, 0x65, 0x22, 0x50, 0x0a, 0x0d, 0x4e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x34, 0x0a, 0x0a, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x5f, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x09, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x54, 0x77, 0x6f, 0x22, 0x64, 0x0a,
	0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x12, 0x0e, 0x0a,
	0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x73, 0x12, 0x0e, 0x0a,
	0x01, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x01, 0x69, 0x12, 0x25, 0x0a,
	0x01, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x01, 0x6d, 0x42, 0x0d, 0x0a, 0x0b, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6f, 0x6e,
	0x65, 0x6f, 0x66, 0x22, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x45, 0x0a,
	0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x6e, 0x69, 0x63, 0x65, 0x31, 0x32, 0x33, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2d, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_messages_proto_rawDescOnce sync.Once
	file_protos_messages_proto_rawDescData = file_protos_messages_proto_rawDesc
)

func file_protos_messages_proto_rawDescGZIP() []byte {
	file_protos_messages_proto_rawDescOnce.Do(func() {
		file_protos_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_messages_proto_rawDescData)
	})
	return file_protos_messages_proto_rawDescData
}

var file_protos_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_messages_proto_goTypes = []interface{}{
	(*SimpleMessage)(nil),       // 0: protos.SimpleMessage
	(*NestedMessage)(nil),       // 1: protos.NestedMessage
	(*DoubleNestedMessage)(nil), // 2: protos.DoubleNestedMessage
	(*MessageOneOf)(nil),        // 3: protos.MessageOneOf
	(*ListMessage)(nil),         // 4: protos.ListMessage
	(*ComplexListMessage)(nil),  // 5: protos.ComplexListMessage
}
var file_protos_messages_proto_depIdxs = []int32{
	0, // 0: protos.NestedMessage.nested:type_name -> protos.SimpleMessage
	1, // 1: protos.DoubleNestedMessage.double_one:type_name -> protos.NestedMessage
	1, // 2: protos.DoubleNestedMessage.double_two:type_name -> protos.NestedMessage
	0, // 3: protos.MessageOneOf.m:type_name -> protos.SimpleMessage
	0, // 4: protos.ListMessage.list:type_name -> protos.SimpleMessage
	2, // 5: protos.ComplexListMessage.list:type_name -> protos.DoubleNestedMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_messages_proto_init() }
func file_protos_messages_proto_init() {
	if File_protos_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleNestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexListMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_messages_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*MessageOneOf_S)(nil),
		(*MessageOneOf_I)(nil),
		(*MessageOneOf_M)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_messages_proto_goTypes,
		DependencyIndexes: file_protos_messages_proto_depIdxs,
		MessageInfos:      file_protos_messages_proto_msgTypes,
	}.Build()
	File_protos_messages_proto = out.File
	file_protos_messages_proto_rawDesc = nil
	file_protos_messages_proto_goTypes = nil
	file_protos_messages_proto_depIdxs = nil
}
